export const GET_SEARCH_QUERY = 'GET_SEARCH_QUERY';
export const RECENT_SEARCH = 'RECENT_SEARCH';
export const SEARCH_DATA = 'SEARCH_DATA';
export const DATA_LOADED = 'DATA_LOADED';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

